### ISSUE TITLE
npm install frida-compile fails to install (dependency of itself)

### ISSUE THREAD

**Issue by cryptax** [frida/frida-compile#12]
I get this error when I run `npm install frida-compile`:

```
npm ERR! Linux 4.13.0-37-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "frida-compile"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ENOSELF

npm ERR! Refusing to install frida-compile as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/axelle/softs/frida-compile/npm-debug.log
```

`npm-debug.log` mentions:
```
verbose stack Error: Refusing to install frida-compile as a dependency of itself
42 verbose stack     at checkSelf (/usr/share/npm/lib/install/validate-args.js:40:14)
42 verbose stack     at Array.<anonymous> (/usr/share/npm/node_modules/slide/lib/bind-actor.js:15:8)
42 verbose stack     at LOOP (/usr/share/npm/node_modules/slide/lib/chain.js:15:14)
42 verbose stack     at chain (/usr/share/npm/node_modules/slide/lib/chain.js:20:5)
42 verbose stack     at /usr/share/npm/lib/install/validate-args.js:15:5
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
42 verbose stack     at Array.forEach (native)
42 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
42 verbose stack     at Array.forEach (native)
42 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
```

**Comment by oleavr** [comment]
Cannot reproduce this. Upgrading to Node.js 10.x / 12.x should solve it.

**Comment by Hellowman** [comment]
Hello @oleavr I am installing Frida-compile and have next error:
```
sh-3.2# npm install frida-compile
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN checkPermissions Missing write access to /
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code EROFS
npm ERR! syscall access
npm ERR! path /
npm ERR! errno -30
npm ERR! rofs EROFS: read-only file system, access '/'
npm ERR! rofs Often virtualized file systems, or other file systems
npm ERR! rofs that don't support symlinks, give this error.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2020-06-16T13_08_44_644Z-debug.log
sh-3.2#
```
___
Mac OS Catalina 10.15.4, node v14.4.0, npm v6.14.4
