### ISSUE TITLE
Windows: TypeError: Cannot read properties of undefined (reading 'options')

### ISSUE THREAD

**Issue by jemeraldo** [frida/frida-compile#46]
```
PS D:\progs\apk\tools\tiktok> npm install --location=global frida-compile
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.

changed 76 packages, and audited 77 packages in 6s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS D:\progs\apk\tools\tiktok> frida-compile -o o.js server.js
TypeError: Cannot read properties of undefined (reading 'options')
    at makeCompilerOptions (file:///C:/Users/jem/AppData/Roaming/npm/node_modules/frida-compile/dist/compiler.js:102:130)
    at Module.build (file:///C:/Users/jem/AppData/Roaming/npm/node_modules/frida-compile/dist/compiler.js:18:26)
    at main (file:///C:/Users/jem/AppData/Roaming/npm/node_modules/frida-compile/dist/cli.js:24:24)
    at file:///C:/Users/jem/AppData/Roaming/npm/node_modules/frida-compile/dist/cli.js:27:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

Windows 10
What could be the problem?

**Comment by oleavr** [comment]
This was fixed a while back. Closing.
