### ISSUE TITLE
Error in frida-agent-example when update to new version.

### ISSUE THREAD

**Issue by huhuang03** [frida/frida-compile#47]
Step to produce:
1. clone [frida-agent-example](https://github.com/oleavr/frida-agent-example)
2. yarn add frida-compile
3. yarn run build

Now error shows:
yarn run v1.22.15
```
$ frida-compile agent/index.ts -o _agent.js -c
Error: unable to resolve: F:\frida-agent-example\agent\logger
    at Object.bundle (file:///F:/frida-agent-example/node_modules/frida-compile/dist/compiler.js:311:23)
    at Module.build (file:///F:/frida-agent-example/node_modules/frida-compile/dist/compiler.js:46:26)
    at main (file:///F:/frida-agent-example/node_modules/frida-compile/dist/cli.js:37:39)
    at file:///F:/frida-agent-example/node_modules/frida-compile/dist/cli.js:56:1
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

**Comment by oleavr** [comment]
Imports must include the `.js` extension; this is exactly like Node.js behaves with ESM modules.
