### ISSUE TITLE
16.1.0 require is not defined

### ISSUE THREAD

**Issue by AeonLucid** [frida/frida-compile#54]
It looks like the frida-compiler v16.1.0 has a shim for the http module. Which tells me that I should be able to use the http module. However, as seen below it does not work.

**Host** Windows 10
**Target** iOS

Code
```typescript
import * as http from 'http';

const host = '0.0.0.0';
const port = 8000;

const requestListener = function (req: any, res: any) {
    res.writeHead(200);
    res.end("My first server!");
};

const server = http.createServer(requestListener);

server.listen(port, host, () => {
    console.log(`Server is running on http://${host}:${port}`);
});
```

Dependencies
```json
"devDependencies": {
  "@types/frida-gum": "^18.1.0",
  "@types/node": "^18.7.18",
  "frida-compile": "^16.1.0"
}
```

Error
```
ReferenceError: require is not defined
    at lookupAndListen (/node_modules/@frida/net/index.js:1146:3)
    at Server.listen (/node_modules/@frida/net/index.js:1127:9)
    at agent/index.ts:33:8
```

**Comment by cohall-2020** [comment]
I'm getting the same "'require' is not defined" error in a different context, so I don't think it's limited to the http module.

**Comment by oleavr** [comment]
@AeonLucid Thanks for reporting! Fixed in 16.1.1, just released.

**Comment by k0ss-test** [comment]
Still having this issue on 16.1.2

**Comment by oleavr** [comment]
> Still having this issue on 16.1.2

Did you make sure that all dependencies are up-to-date? (Wipe any `package-lock.json` and `node_modules/`, and do `npm install` again.)

**Comment by k0ss-test** [comment]
Specifically I'm trying to follow these instructions https://github.com/frida/frida/issues/1200#issuecomment-708481574 .

I did:
```bash
rm -rf node_modules/ package_lock.json
# add "demangler-js" : "0.1.7" to package.json in vim...
npm install
npm install frida-compile demangler-js -g # just in case
frida -l _agent.js -H x.x.x.x /bin/program
# ReferenceError: 'require' is not defined
#.   at <anonymous> (index.ts:2)
```
My `index.ts` looks like
```typescript
const demangle = require('demangler-js').demangle;
const nm = DebugSymbol.fromAddress(DebugSymbol.findFunctionsMatching("_ZN*")[0]).name;
console.log(`Before: ${nm}\nAfter: ${demangle(nm)}`);
```

**Comment by 0MrError0** [comment]
same issue
