### ISSUE TITLE
Unable to resolve local module on 16.1.10

### ISSUE THREAD

**Issue by AeonLucid** [frida/frida-compile#55]
**Host** Windows 10
**Target** iOS

**index.ts**
```typescript
import { blabla } from "./utils";

blabla();
```

**utils.ts**
```typescript
export function blabla() {
    console.log('Hi');
}
```

Error
```
Error: unable to resolve: E:/Aeon/agent/utils
    at Object.bundle (file:///E:/Aeon/node_modules/frida-compile/dist/compiler.js:324:23)
    at Module.build (file:///E:/Aeon/node_modules/frida-compile/dist/compiler.js:47:20)
    at main (file:///E:/Aeon/node_modules/frida-compile/dist/cli.js:37:33)
    at file:///E:/Aeon/node_modules/frida-compile/dist/cli.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12)
```

**Comment by oleavr** [comment]
> import { blabla } from "./utils";

Should be:

> import { blabla } from "./utils.js";

(Like Node.js we require the extension to be explicitly provided.)

**Comment by AeonLucid** [comment]
Shouldn't it be .ts?

**Comment by oleavr** [comment]
No, it's the compiled name (which is a bit confusing indeed).

**Comment by 0x5e** [comment]
can it be automatically converted?

**Comment by oleavr** [comment]
@0x5e There's no need, the TypeScript compiler understands it and expects it that way.
