### ISSUE TITLE
frida-compile does not work with external modules

### ISSUE THREAD

**Issue by Ouroboros** [frida/frida-compile#61]
### frida-compile version:
16.1.5

### OS:
Windows 11

#### test.ts
```
import { parse } from 'json5';

console.log(parse);
```

#### compile cmd:
`frida-compile test.ts -o test.js`

#### frida output
```
SyntaxError: Could not find export 'parse' in module '/node_modules/json5/dist/index.mjs'
```

This code works on frida-compile 10.2.5

**Comment by mjak96** [comment]
I have similar issue.

**Comment by artakvg** [comment]
I am getting this when trying to run a simple thing. 

1. I have a demo.js with just a console.log("Hello World");

2. and then I have compiled this with `frida-compile -o demo--compiled demo.js`

3. Once I have the compiled version I am just running the Calculataor app in my iPhone and then finding the process ID with 
`frida-ps -U | grep "Calculator"`

4. Once i got the pid .. I am doing this  `frida --runtime=v8 -U  -l a -p 5332`

And getting this error 

```bash
Exception in thread Thread-1 (_run):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/frida_tools/reactor.py", line 70, in _run
    work()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/frida_tools/application.py", line 599, in _try_start
    self._start()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/frida_tools/repl.py", line 220, in _start
    self._set_autoperform(self._autoperform_option)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/frida_tools/repl.py", line 611, in _set_autoperform
    if self._is_java_available():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/frida_tools/repl.py", line 619, in _is_java_available
    script = self._session.create_script(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/frida/core.py", line 86, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/frida/core.py", line 628, in create_script
    return Script(self._impl.create_script(source, **kwargs))  # type: ignore
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
frida.TransportError: the connection is closed
```

P.S. I have Java,, node and python3 on my macos

**Comment by kursattkorkmazzz** [comment]
same problem :(

**Comment by kursattkorkmazzz** [comment]
@rubenvereecken 
I just install using `npm i -D esbuild`

My tsconfig look like;

```
{
  "compilerOptions": {
    "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include 
    "module": "CommonJS",                                /* Specify what module code is generated. */
    "rootDir": "./src",                                  /* Specify the root folder within your source files. */
     "resolveJsonModule": true,                        /* Enable importing .json files. */
     "allowJs": true,                                  /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get
     "checkJs": true,                                  /* Enable error reporting in type-checked JavaScript files. */
     "outDir": "./dist",                                   /* Specify an output folder for all emitted files. */
     "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. 
    "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */
    "strict": true,                                      /* Enable all strict type-checking options. */
    "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
  }
}
```

My package.json scripts look likse;

```
  "scripts": {
    "build": "esbuild ./src/main.ts --bundle  --platform=node --outfile=./dist/main-esbuild.js",
    "watch": "esbuild ./src/main.ts --bundle --platform=node --outfile=./dist/main-esbuild.js --watch",
    "frida": "frida -U -f re.frida.Gadget -l ./dist/main-esbuild.js"
  }
```

And it just worked.

**Comment by rubenvereecken** [comment]
@kursattkorkmazzz I'm really surprised you got that to work – what do your `import`s get compiled to?

Because reusing your `tsconfig` and esbuild command, I still get `require`s in the final script, which frida doesn't like:
```
ReferenceError: 'require' is not defined
    at <eval> (dist/esbuild.js:3110)
```

I also tried `--runtime=v8`, but same problem. That's on `frida v16.5.6`.

Wondering whether it's got something to do with you loading `re.frida.Gadget` rather than injecting. That's the only difference I can see (assuming your compiled script still uses `require`).

**Comment by kursattkorkmazzz** [comment]
Actually my output doesn't contain any import or require terms. All codes are built into one file. 

This is my example output file how looks like: [Drive](https://drive.google.com/file/d/1fRBM6rJbo2oDB3mPkJUIa0fvTzDctVgv/view?usp=sharing)

----

Because my device is not rooted, I prefer to choose gadget. I know that (not sure), even I use re.frida.gadget, It uses script to injecting. So, your build file shouldn't contain any import or require statment as mine. You may need to adjust your configuration.

**Comment by rubenvereecken** [comment]
@kursattkorkmazzz amazing, thanks for all this help and input!

I should have dug deeper. Yes, I'm using `--bundle`, which apparently really should combine everything into one self-contained JS file. But on closer inspection, two modules are resisting this: `common/file.ts` from frida itself and `frida-fs`. All the others are successfully compiled without `require`. I'll do a bit more digging later to see what I can do about these!

**Comment by athlan20** [comment]
> [@rubenvereecken](https://github.com/rubenvereecken) I just install using `npm i -D esbuild`
> 
> My tsconfig look like;
> 
> ```
> {
>   "compilerOptions": {
>     "target": "es2016",                                  /* Set the JavaScript language version for emitted JavaScript and include 
>     "module": "CommonJS",                                /* Specify what module code is generated. */
>     "rootDir": "./src",                                  /* Specify the root folder within your source files. */
>      "resolveJsonModule": true,                        /* Enable importing .json files. */
>      "allowJs": true,                                  /* Allow JavaScript files to be a part of your program. Use the 'checkJS' option to get
>      "checkJs": true,                                  /* Enable error reporting in type-checked JavaScript files. */
>      "outDir": "./dist",                                   /* Specify an output folder for all emitted files. */
>      "esModuleInterop": true,                             /* Emit additional JavaScript to ease support for importing CommonJS modules. 
>     "forceConsistentCasingInFileNames": true,            /* Ensure that casing is correct in imports. */
>     "strict": true,                                      /* Enable all strict type-checking options. */
>     "skipLibCheck": true                                 /* Skip type checking all .d.ts files. */
>   }
> }
> ```
> 
> My package.json scripts look likse;
> 
> ```
>   "scripts": {
>     "build": "esbuild ./src/main.ts --bundle  --platform=node --outfile=./dist/main-esbuild.js",
>     "watch": "esbuild ./src/main.ts --bundle --platform=node --outfile=./dist/main-esbuild.js --watch",
>     "frida": "frida -U -f re.frida.Gadget -l ./dist/main-esbuild.js"
>   }
> ```
> 
> And it just worked. But don't forget the `--platform=node` and `--bundle` parameters for esbuild.

really nice,it works for me,thanks
