### ISSUE TITLE
Error during frida-compile.

### ISSUE THREAD

**Issue by abdelaziz-khaled** [frida/frida-compile#77]
CMD : frida-compile script.js -o run.js
Error: Unable to detect shim directory; please file a bug
    at Module.queryDefaultAssets (file:///C:/Users/user1/AppData/Roaming/npm/node_modules/frida-compile/dist/compiler.js:161:19)
    at main (file:///C:/Users/user1/AppData/Roaming/npm/node_modules/frida-compile/dist/cli.js:23:29)
    at file:///C:/Users/user1/AppData/Roaming/npm/node_modules/frida-compile/dist/cli.js:57:5
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

**Comment by abdelaziz-khaled** [comment]
The problem arose due to a space in the file path.
