### ISSUE TITLE
 Error: entrypoint must be inside the project root

### ISSUE THREAD

**Issue by Wen-Lv** [frida/frida-compile#90]
Error: entrypoint must be inside the project root  at deriveEntrypoint (file:///opt/homebrew/lib/node_modules/frida-compile/dist/compiler.js:131:15)  at Module.build (file:///opt/homebrew/lib/node_modules/frida-compile/dist/compiler.js:16:24)  at main (file:///opt/homebrew/lib/node_modules/frida-compile/dist/cli.js:37:33)  at file:///opt/homebrew/lib/node_modules/frida-compile/dist/cli.js:57:5  at ModuleJob.run (node:internal/modules/esm/module_job:222:25)  at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)  at async loadESM (node:internal/process/esm_loader:28:7)  at async handleMainPromise (node:internal/modules/run_main:113:12)  Error during frida-compile, potentially caused by compilation errors. Aborting. If exception details are not returned, try to run frida-compile manually. frida-compile command:  "/opt/homebrew/bin/frida-compile" -o "/Users/qiangbaobao/tools/burpchajian/brida/brida.js/bridaGeneratedCompiledOutput.js" "/Users/qiangbaobao/tools/burpchajian/brida/brida.js/brida.js"

**Comment by xax** [comment]
Duplicate of #82.
